project_identifier: joomla-patchtester
api_key_env: 'CROWDIN_API_KEY'
base_path: ./components/com_apps/language

files:
  -
    source: /en-GB/en-GB.com_apps.ini
    dest: 'Install from Web/en-GB.com_apps.ini'
    translation: /%locale%/%locale%.com_apps.ini
