# Project Public Identifier: joomla-official-extensions
project_id: 104
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: 
base_url: "https://joomla.crowdin.com"

preserve_hierarchy: true

files:
  - source: /components/com_apps/language/en-GB/en-GB.com_apps.ini
    dest: 'InstallFromWeb/site/en-GB.com_apps.ini'
    translation: /components/com_apps/language/%locale%/%locale%.com_apps.ini
    type: joomla
    update_option: update_as_unapproved
